### ISSUE TITLE
How to uninstall feature?

### ISSUE THREAD

**Issue by alexei** [maxtepkeev/architect#42]
I decorated a model with `@architect.uninstall('partition')` then ran `architect partition --module myapp.models` with the following result:
```
Traceback (most recent call last):
  File "~/.virtualenvs/myproject/bin/architect", line 11, in <module>
    sys.exit(main())
  File "~/.virtualenvs/myproject/lib/python2.7/site-packages/architect/commands/__init__.py", line 93, in main
    commands[command]['parser'].result(args.func(vars(args)))
  File "~/.virtualenvs/myproject/lib/python2.7/site-packages/architect/commands/partition.py", line 26, in run
    module_clss = filter(lambda obj: isinstance(obj, type), __import__(module, fromlist=module).__dict__.values())
  File "~/Projects/myproject/myapp/models/__init__.py", line 8, in <module>
    from .mymodels import *  # noqa
  File "~/Projects/myproject/myapp/models/mymodels.py", line 1048, in <module>
    class MyModel(BaseModel):
  File "~/.virtualenvs/myproject/lib/python2.7/site-packages/architect/orms/decorators.py", line 155, in __call__
    self.deinit_feature(self.feature, model)
  File "~/.virtualenvs/myproject/lib/python2.7/site-packages/architect/orms/decorators.py", line 171, in deinit_feature
    allowed=[name for name, obj in model.architect.__dict__.items() if isinstance(obj, BaseFeature)])
AttributeError: type object 'MyModel' has no attribute 'architect'
```
I might be doing something wrong. The docs seem a tad too brief, though :)

**Comment by maxtepkeev** [comment]
Yes, ``uninstall`` decorator doesn't work in that way, it is used when you need to remove a feature during runtime, there is an example given in the when this can useful [docs](http://architect.readthedocs.io/features/index.html#uninstall). If you want to remove created partitions on database level this should be done by hand.

**Comment by alexei** [comment]
Oh, I see. I wasn't expecting it to deal with partitions as that would be difficult. I was, however, expecting it to delete the triggers and stuff. Would that be impossible?

**Comment by maxtepkeev** [comment]
Unfortunately no. Right now it doesn't to anything at the database level, only during runtime. So if you want to remove triggers, the only way is to that manually.

**Comment by akuisara** [comment]
Hi @maxtepkeev how to manually remove the triggers?
