### ISSUE TITLE
syntax error is coming when creating partition of my table

### ISSUE THREAD

**Issue by nehaghub** [maxtepkeev/architect#63]
Hi,
Please check below error is coming
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neha/venvs/django-env/bin/architect", line 10, in <module>
    sys.exit(main())
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/architect/commands/__init__.py", line 93, in main
    commands[command]['parser'].result(args.func(vars(args)))
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/architect/commands/partition.py", line 32, in run
    cls.architect.partition.get_partition().prepare()
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/architect/databases/postgresql/partition.py", line 107, in prepare
    column='"{0}"'.format(self.column_name)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/architect/orms/django/features.py", line 48, in execute
    return self.connection.execute(sql)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/neha/venvs/django-env/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: syntax error at or near "_insert_child"
LINE 3: ...REATE OR REPLACE FUNCTION "general"."email_master"_insert_ch...
                                                             ^

when i am trying to run command
architect partition --module ti_webapp.models.EmailMaster

my configurations are
addict                        2.2.0     
alabaster                     0.7.3     
architect                     0.5.6     
Babel                         2.6.0     
beautifulsoup4                4.7.1     
blessings                     1.7       
bpython                       0.17.1    
bs4                           0.0.1     
certifi                       2018.11.29
chardet                       3.0.4     
curtsies                      0.3.0     
Django                        2.1.7     
django-composite-foreignkey   1.1.0     
django-redis                  4.10.0    
django-redis-sessions         0.6.1     
docutils                      0.14      
Dumper                        1.2.0     
elasticsearch                 1.9.0     
greenlet                      0.4.15    
idna                          2.8       
imagesize                     1.1.0     
Jinja2                        2.10      
MarkupSafe                    1.1.1     
nltk                          3.4       
packaging                     19.0      
pip                           19.0.3    
pkg-resources                 0.0.0     
psycopg2                      2.7.7     
psycopg2-binary               2.7.7     
pycrypto                      2.6.1     
Pygments                      2.3.1     
pyketama                      0.2.1     
pyparsing                     2.3.1     
python-decouple               3.1       
python-memcached              1.59      
pytz                          2018.9    
redis                         3.2.0     
requests                      2.21.0    
setuptools                    40.8.0    
simple-crypt                  4.1.7     
simplejson                    3.16.0    
singledispatch                3.4.0.3   
six                           1.12.0    
snowballstemmer               1.2.1     
soupsieve                     1.9       
Sphinx                        2.0.0     
sphinxcontrib-applehelp       1.0.1     
sphinxcontrib-devhelp         1.0.1     
sphinxcontrib-htmlhelp        1.0.1     
sphinxcontrib-jsmath          1.0.1     
sphinxcontrib-qthelp          1.0.2     
sphinxcontrib-serializinghtml 1.1.1     
typing                        3.6.6     
urllib3                       1.24.1    
wcwidth                       0.1.7     
wheel                         0.33.0

**Comment by maxtepkeev** [comment]
Does v0.6.0 solve your issue ?
